apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo"
spec:
  selector:
    matchLabels:
      app: "todo"
  replicas: 5
  template:
    metadata:
      labels:
        app: "todo"
    spec:
      containers:
      - image: {{ .Values.dockerImage }}
        imagePullPolicy: Always
        name: "todo-app"
        env:
          - name: DB_ENDPOINT
            value: {{ .Values.db_endpoint }}
          - name: DB_USERNAME
            value: {{ .Values.db_user }}
          - name: DB_PASSWORD
            value: {{ .Values.db_pass }}
        ports:
        - containerPort: 5000